### ISSUE TITLE
HiFi avatars bones are not Hifi compatible

### ISSUE THREAD

**Issue by JulianGro** [KawaneRio/blender-chan#2]
The Hifi and Vircadia avatars are both not compatible with Hifi/Vircadia.
The bone naming is incompatible and the `.fst` doesn't remap them.
The best way to fix this would be to rename the bones in Blender according to: https://docs.vircadia.com/create/avatars/avatar-standards.html#skeleton

Keep in mind that an fst file is optional and only needed for remapping bones, attaching scripts, or adding "flow".

**Comment by KawaneRio** [comment]
ぐわーーーーーーーーーーーーーーーーーーーーー
