### ISSUE TITLE
Hifi compatible avatars should embed textures

### ISSUE THREAD

**Issue by JulianGro** [KawaneRio/blender-chan#3]
When exporting an avatar for Hifi it makes sense to embed the textures. This makes it easier to use and faster to load.

Here are some example export settings with some explanations:
![1Blender File View_932_e](https://user-images.githubusercontent.com/11144627/134803444-d8b7bedf-9d26-49ad-951e-3a45816ade3e.png)

- (1) You should save your settings in a preset to make it easier to export the avatar for testing. (This preset does not update and has to be overwritten when you change something)
- (2) Setting the "Path mode" to "Copy" and checking the box next to it, embeds the textures into the exported FBX file.
- (3) Blender adds leaf bones by standard which are useless, make stuff more confusing to work with, and I think even get updates through Hifi's avatar mixer and therefore use slightly more bandwidth.

**Comment by KawaneRio** [comment]
I've tried doing this, but it had failed me every time. Switching to .glb file instead of fbx.

**Comment by KawaneRio** [comment]
The latest .glb works with textures. Closing the issue :smiling_face_with_three_hearts:
